on:
  release:
    types: [created]
  push:

jobs:
  release:
    if: github.event_name == 'release'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          EXTRA_FILES: README.md
          ARCHIVE_TYPES: zip
          MINIFY: true
  build:
    name: Attempt build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: View result
        run: ls -laR
