on:
  push:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Run cargo build
        run: cargo build --release
      - name: Build a zip
        run: |
          mkdir temp;
          cp target/release/rust-serial-controller.exe temp;
          cp README.md temp;
          cd temp;
          C:\Program` Files\7-Zip\7z.exe a ../release.zip *;
          cd ..;
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
  build:
    name: Check project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          